name: nlpiaenv

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - beautifulsoup4
  - boto3
  - botocore
  - django
  - django-environ
  - django-extensions
  - gitpython
  - gcc
  - html5lib
  - hunspell
  - hunspell-en
  - ipython
  - jupyter
  - jupyter_core<4.6.0
  - keras
  - libgcc
  - matplotlib
  - mysqlclient
  - nltk
  - pandas
  - pandoc
  - pip>=19.0
  - plotly
  - pre-commit
  - prompt_toolkit
  - psycopg2
  - pyscaffold
  - pytest-cov
  - python-levenshtein
  - python=3.7
  - redis-py
  - regex==2018.1.10
  - scipy
  - spacy==2.2.2
  - sqlparse
  - tensorflow==1.13.1

  - pip:
    - wikipedia-api
    - nlpia
