name: nlpiaenv

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - boto3
  - botocore
  - django
  - django-environ
  - django-extensions
  - gitpython
  - hunspell
  - hunspell-en
  - jupyter
  - keras
  # - msgpack<0.6.0,>=0.5.6
  - mysqlclient
  - nltk
  - pandas
  - pandoc
  - pip>=19.0
  - plotly
  - pre-commit
  - psycopg2
  # - pyasn1  # jupyter
  - pyscaffold
  - pytest-cov
  - python-levenshtein
  - python=3.7
  - redis-py
  - regex==2018.1.10
  - scipy
  - spacy==2.0.12
  - sqlparse
  - tensorflow==1.13.1
  # - twisted  # jupyter

  - pip:
    - wikipedia-api
    - nlpia
    # - msgpack<0.6.0,>=0.5.6
