name: nlpiaenv

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - beautifulsoup4
  - boto3
  - botocore
  - ConfigArgParse
  - django
  - django-environ
  - django-extensions
  - gitpython
  # - gcc
  - html5lib
  # - hunspell
  # - hunspell-en
  # - ipython
  - jupyter
  # - jupyter_core
  # - jupyter_console
  - keras
  # - libgcc
  - matplotlib
  - mysqlclient
  - nbconvert
  - nltk
  - pandas
  - pandoc
  - pip
  - plotly
  - pre-commit
  - prompt_toolkit
  - psycopg2
  - pyscaffold
  - pytest-cov
  - python-levenshtein
  - python=3.7
  - redis-py
  - regex  # ==2018.1.10
  - scipy
  - spacy>=2.2.2
  - sqlparse
  - tensorflow  # ==1.13.1

  - pip:
    - wikipedia-api
    - fuzzywuzzy
    # - nlpia
    # - msgpack<0.6.0,>=0.5.6
