name: nlpiaenv

channels:
  - conda-forge  # conda-forge is higher priority than defaults in nlpia package
  - defaults  # top priority: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#managing-channels
  # - anaconda  # bad idea: https://github.com/conda/conda/issues/9462

dependencies:
  - beautifulsoup4
  - boto3
  - botocore
  - ConfigArgParse
  - django
  - django-environ
  - django-extensions
  - gitpython
  # - gcc
  - html5lib
  - hunspell
  - hunspell-en
  # - ipython
  - jupyter
  # - jupyter_core
  # - jupyter_console
  # - keras
  # - libgcc
  - lxml
  # - matplotlib
  - mysqlclient
  - nbconvert
  - nltk
  - pandas
  - pandoc
  - pip
  - plotly
  - pre-commit
  - prompt_toolkit<3.0
  - psycopg2
  - pyscaffold
  - pytest-cov
  - python-levenshtein
  - python=3.8
  - redis-py
  - regex  # ==2018.1.10
  - scipy
  - spacy>=2.2.2
  - sqlparse
  # - tensorflow==2.0  # ==1.13.1

  - pip:
    - wikipedia-api
    - environment
    - fuzzywuzzy
    # - nlpia
